### ISSUE TITLE
项目缺少GalaSoft.MvvmLight

### ISSUE THREAD

**Issue by KaneLeung** [AFei19911012/HandyControlDemo#1]
你好，项目中缺少GalaSoft.MvvmLight无法运行，想替换成NuGet的GalaSoft.MvvmLight包也不支持。

**Comment by AFei19911012** [comment]
邮件已收到。

**Comment by KaneLeung** [comment]
找到了https://github.com/AFei19911012/GalaSoft.MvvmLight
