### ISSUE TITLE
How to build this project?

### ISSUE THREAD

**Issue by Anestis271** [AFei19911012/HandyControlDemo#2]
I've tried to bulid this project (use both VS 2022 and Rider 2023.1), but all failed. I found the missing of Galasoft.MvvmLight package, so I tried to add the package via nuget, but only partially resolved the error. I don't know how to resolve the other errors.
I need to know how to build this project correctly, thank you!

**Comment by AFei19911012** [comment]
邮件已收到。

**Comment by AFei19911012** [comment]
> I've tried to bulid this project (use both VS 2022 and Rider 2023.1), but all failed. I found the missing of Galasoft.MvvmLight package, so I tried to add the package via nuget, but only partially resolved the error. I don't know how to resolve the other errors. I need to know how to build this project correctly, thank you!

download this shared project and put it in the same folder https://github.com/AFei19911012/GalaSoft.MvvmLight

**Comment by Anestis271** [comment]
Thank you for your help!

**Comment by Anestis271** [comment]
添加 Shared project 解决了大部分问题，但仍然有错误存在。
无法解析符号 'data' 和 无法解析符号 'CardModel'
在 UserControl\Card.xaml 中

**Comment by Anestis271** [comment]
我自己在Model中添加了CardModel.cs，问题已经解决了，感谢！
