### ISSUE TITLE
拉取项目下本地报错

### ISSUE THREAD

**Issue by MiaoWei814** [AFei19911012/HandyControlDemo#4]
你好 我在知乎上看你还没回 我想在这或许能寻求到您 能帮忙解决一下吗 我也不知道如何解决了

**Comment by AFei19911012** [comment]
邮件已收到。

**Comment by MiaoWei814** [comment]
![v2-c78c90722daf826c0c3363cd1099ff9e_r](https://github.com/AFei19911012/HandyControlDemo/assets/72567951/dff0f44b-803f-4d68-a064-f8242dd76664)

**Comment by MiaoWei814** [comment]
非常谢谢您 主要想快速学习一下那个ui库的源码学习

**Comment by AFei19911012** [comment]
问题是否解决？


> ![v2-c78c90722daf826c0c3363cd1099ff9e_r](https://private-user-images.githubusercontent.com/72567951/290062825-dff0f44b-803f-4d68-a064-f8242dd76664.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3MzU5NDIsIm5iZiI6MTcwMjczNTY0MiwicGF0aCI6Ii83MjU2Nzk1MS8yOTAwNjI4MjUtZGZmMGY0NGItODAzZi00ZDY4LWEwNjQtZjgyNDJkZDc2NjY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE2VDE0MDcyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJiNjQ3MzRlNDhmYTlmNjRlYjVmZTUyZmUzOTFlYjZjZDkwMTRiZTQzNjQyYjBiMmI2ODc1N2MyOGMwMDI2ODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.q8sBkOM5Mm6XS94C3GR_fvxRLt8YDOYn1fUxyILV8HM)

**Comment by Chaoray** [comment]
@AFei19911012 请问是怎么解决的呢？我这边也出现了一样的问题，謝謝！

**Comment by AFei19911012** [comment]
> @AFei19911012 请问是怎么解决的呢？我这边也出现了一样的问题，謝謝！

目前项目的目标框架是 4.7.2，是否需要先修改成这个框架，或者升级？

**Comment by MiaoWei814** [comment]
我这边已经解决了 解决思路是删除了项目中的已有的引用依赖HandyControl然后重新进行引用了一下就可以了
